package com.example.health_care_system.repository;

import com.example.health_care_system.model.AnalyticsReport;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface AnalyticsReportRepository extends MongoRepository<AnalyticsReport, String> {
    
    // Find by report ID
    Optional<AnalyticsReport> findByReportId(String reportId);
    
    // Find by report type
    List<AnalyticsReport> findByReportType(AnalyticsReport.ReportType reportType);
    
    // Find by generated by user
    List<AnalyticsReport> findByGeneratedBy(String generatedBy);
    
    // Find reports generated within a date range
    List<AnalyticsReport> findByGeneratedAtBetween(LocalDateTime start, LocalDateTime end);
    
    // Find reports by type and date range
    List<AnalyticsReport> findByReportTypeAndGeneratedAtBetween(
        AnalyticsReport.ReportType reportType, 
        LocalDateTime start, 
        LocalDateTime end
    );
    
    // Find latest reports by type
    List<AnalyticsReport> findTop10ByReportTypeOrderByGeneratedAtDesc(AnalyticsReport.ReportType reportType);
    
    // Find all reports ordered by generation date (most recent first)
    List<AnalyticsReport> findAllByOrderByGeneratedAtDesc();
    
    // Check if report exists by reportId
    boolean existsByReportId(String reportId);
    
    // Delete old reports before a specific date
    void deleteByGeneratedAtBefore(LocalDateTime date);
}
